### ISSUE TITLE
Microsoft.VisualStudio.Coverage.Monitor.pdb bug

### ISSUE THREAD

**Issue by icyfox168168** [MolecularMatters/raw_pdb#68]
S_LPROC32 Function 'DuplicateLoggerBuffer' | RVA 0x1C70
    S_LOCAL: 'CProfileMonitorControl' -> 'ProfileMonitorControl'
    S_DEFRANGE_REGISTER: Register 0x 14A
    S_DEFRANGE_REGISTER: Register 0x 14C
    S_LOCAL: 'CLoggerBuffer' -> 'SourceBuffer'
    S_DEFRANGE_REGISTER: Register 0x 14B
    S_DEFRANGE_REGISTER: Register 0x 14E
    S_LOCAL: '_GUID' -> 'ExecGuid'
    S_DEFRANGE_REGISTER: Register 0x 150
    S_DEFRANGE_REGISTER: Register 0x 156
    S_LOCAL: '_BUFFERHEADER' -> 'DuplicateBufferHeader'
    S_DEFRANGE_REGISTER: Register 0x 151
    S_LOCAL: 'CLoggerBuffer' -> 'DuplicateBuffer'
    S_DEFRANGE_REGISTER: Register 0x 14D
    S_LOCAL: 'PUCHAR' -> 'SourceCoverageData'
    S_DEFRANGE_REGISTER: Register 0x 14B
    S_LOCAL: 'PUCHAR' -> 'DuplicateCoverageData'
    S_DEFRANGE_REGISTER: Register 0x 14A
    S_LOCAL: '_BUFFERHEADER' -> 'SourceBufferHeader'
    S_DEFRANGE_REGISTER: Register 0x 14B
    S_INLINESITE: Parent 0x 5A7C
        S_INLINESITE: Parent 0x 5C60
            S_LOCAL: 'ULONG' -> 'dwHandle'
            S_DEFRANGE_REGISTER: Register 0x 14

https://ufile.io/846wqrra

**Comment by MolecularMatters** [comment]
Can you please provide more information when submitting an issue?
The description says "Microsoft.VisualStudio.Coverage.Monitor.pdb bug", but I don't see what's wrong.

It would be nice if you could describe what you're expecting to see, what's happening, what the actual bug is, etc.

**Comment by icyfox168168** [comment]
Problem with pointer, unable to run from start to finish

**Comment by icyfox168168** [comment]
You can download the PDB file and run it once to find out where the error is

**Comment by icyfox168168** [comment]
Can you reproduce it? The program cannot parse this PDB and will crash,

**Comment by lukekasz** [comment]
I did a quick debugging session on this PDB and there are some odd things about it.

It crashes because there is a `S_LOCAL` which has a type index `0x80100011`, yet there are only `0x8795` types in the PDB. Also, this `0x80100011` looks like a bit mask and not a type index to me. Not sure why `S_LOCAL` would have this value for its type index and I wasn't able to find any hints in the [microsoft-pdb](https://github.com/microsoft/microsoft-pdb) repo.

If I handle this out of bounds type index gracefully and return `type_index_out_of_range` for the type name, then I get the following output for function variables in the function that crashes

```
S_LPROC32 Function 'DuplicateLoggerBuffer' | RVA 0x1C70
    S_LOCAL: 'CProfileMonitorControl' -> 'ProfileMonitorControl' | Param: True | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 330
    S_DEFRANGE_REGISTER: Register 332
    S_LOCAL: 'CLoggerBuffer' -> 'SourceBuffer' | Param: True | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 331
    S_DEFRANGE_REGISTER: Register 334
    S_LOCAL: '_GUID' -> 'ExecGuid' | Param: True | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 336
    S_DEFRANGE_REGISTER: Register 342
    S_LOCAL: '_BUFFERHEADER' -> 'DuplicateBufferHeader' | Param: False | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 337
    S_LOCAL: 'CLoggerBuffer' -> 'DuplicateBuffer' | Param: False | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 333
    S_LOCAL: 'PUCHAR' -> 'SourceCoverageData' | Param: False | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 331
    S_LOCAL: 'PUCHAR' -> 'DuplicateCoverageData' | Param: False | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 330
    S_LOCAL: '_BUFFERHEADER' -> 'SourceBufferHeader' | Param: False | Optimized Out: False
    S_DEFRANGE_REGISTER: Register 331
    S_INLINESITE: Parent 0x5A7C
        S_INLINESITE: Parent 0x5C60
            S_LOCAL: 'ULONG' -> 'dwHandle' | Param: False | Optimized Out: False
            S_DEFRANGE_REGISTER: Register 20
            S_LOCAL: 'type_index_out_of_range' -> 'pbuf' | Param: False | Optimized Out: False
            S_DEFRANGE_REGISTER: Register 333
            S_DEFRANGE_REGISTER: Register 333
            S_INLINESITE: Parent 0x5C78
                S_CALLEES: Count 1
                S_LOCAL: 'type_index_out_of_range' -> 'pbuf' | Param: False | Optimized Out: False
                S_DEFRANGE_REGISTER: Register 328
                S_DEFRANGE_REGISTER: Register 328
                S_INLINESITE: Parent 0x5CF8
                S_INLINESITE_END:
            S_INLINESITE_END:
            S_INLINESITE: Parent 0x5C78
            S_INLINESITE_END:
        S_INLINESITE_END:
    S_INLINESITE_END:
    S_INLINESITE: Parent 0x5A7C
    S_INLINESITE_END:
    S_INLINESITE: Parent 0x5A7C
    S_INLINESITE_END:
    S_FRAMEPROC: Size 32 | Padding 0 | Padding Offset 0x0 | Callee Registers Size 24
    S_INLINEES: Count 14
    S_LABEL32: '$LN34' | Offset 0xD91
    S_REGREL32: 'ProfileMonitorControl' -> 'CProfileMonitorControl' | Register 335 | Register Offset 0x40
    S_REGREL32: 'SourceBuffer' -> 'CLoggerBuffer' | Register 335 | Register Offset 0x48
    S_REGREL32: 'ExecGuid' -> '_GUID' | Register 335 | Register Offset 0x50
    S_CALLSITEINFO: 'type_index_out_of_range' | Offset 0xC98 | Section 1
    S_CALLSITEINFO: 'type_index_out_of_range' | Offset 0xCBC | Section 1
S_END
```
As you can see, there are multiple `type_index_out_of_range` in the output for the function.

Even after this change, it hits asserts due to `Unhandled record kind 0x117F with block level 1`. I'm unable to find any information on record kind `0x117F`.

I then tried running this pdb through [llvm-debuginfo-analyzer](https://llvm.org/docs/CommandGuide/llvm-debuginfo-analyzer.html) and it just crashes on the PDB.

I also tried running it throught dia2dump, but it appears it does not print the function variables/scopes. 

- Output: [Microsoft.VisualStudio.Coverage.Monitor-dia2dump.txt](https://github.com/MolecularMatters/raw_pdb/files/12856073/Microsoft.VisualStudio.Coverage.Monitor-dia2dump.txt). 

You can search for the crashing function `DuplicateLoggerBuffer` in the dia2dump output and see it provides no details about the variables in functions.

A deeper investigation of the PDB be is required to figure out exactly what is going on. Maybe writing a parser with the DIA SDK could be a way forward to help understand what is going on :-)
